name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::905418427814:role/github-actions-projeto-gitactions-aws"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "gabriel-sa-east-1-statefile"
      aws-lock-dynamodb-table: "gabriel-sa-east-1-terraform-lock"